application.name: Flow Manager

server:
  #port: 8080
  http.port: 8080
  https.port: 8443
  port: 8443
  ssl:
    enabled: true
    key-alias: ${APP_HOSTNAME}
    key-password: ${KEYSTOREPASSWORD}
    key-store: classpath:private/flowManagerBot.jks
    key-store-provider: SUN
    key-store-type: JKS
    key-store-password: ${KEYSTOREPASSWORD}

external.webhook.url: https://${APP_HOSTNAME}:${server.https.port}
internal.webhook.url: https://${APP_HOSTNAME}:${server.https.port}

info.app.maven.version: @pom.version@
info.app.maven.artifactId: @pom.artifactId@
info.app.maven.groupId: @pom.groupId@

logging.config: classpath:logback.xml

security:
  basic:
    enabled: false

oauth2.redirect.uri: https://${APP_HOSTNAME}:${server.https.port}/flow-manager/oauth2Callback
spring.data.mongodb.uri: ${MONGODB_URI}

google:
  client:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
    accessTokenUri: https://accounts.google.com/o/oauth2/token # https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true